### PR TITLE
Shortened mkdir command for data directory

### PR DESCRIPTION
**Pull request by Zero-1729**
Shortened and added required root permissions for mkdir command

### CODE REVIEW

**Comment by alexbosworth** [comment]
I don't think it should require sudo

**Comment by Zero-1729** [comment]
I got the permissions error on one of my ec2 instances:

**Comment by alexbosworth** [comment]
if you do `ls -alF /` what does it show for `chain`? It is root/root?

**Comment by Zero-1729** [comment]
Yes, after creating it with `sudo` and running `ls -alF /` it shows up as `root root`.

**Comment by alexbosworth** [comment]
I think it doesn't need to be created as sudo, although maybe it should be a different user generally I think it's good to avoid sudo/root

**Comment by Zero-1729** [comment]
Fair enough, I suppose `sudo` might be overkill in this scenario.

**Comment by alexbosworth** [comment]
I think maybe you didn't do the chown command step that's why it's root/root and not user/root

**Comment by Zero-1729** [comment]
I skipped the attached disk setup bit (I am storing the chain on the main drive), so I suppose that contributed/had something to do with it.

**Pull request merged**
